//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHC.WaterFeeWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonUser", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTOAuth")]
    [System.SerializableAttribute()]
    public partial class LogonUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntComIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntDeptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExpireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntComID {
            get {
                return this.IntComIDField;
            }
            set {
                if ((this.IntComIDField.Equals(value) != true)) {
                    this.IntComIDField = value;
                    this.RaisePropertyChanged("IntComID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntDeptID {
            get {
                return this.IntDeptIDField;
            }
            set {
                if ((this.IntDeptIDField.Equals(value) != true)) {
                    this.IntDeptIDField = value;
                    this.RaisePropertyChanged("IntDeptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntID {
            get {
                return this.IntIDField;
            }
            set {
                if ((this.IntIDField.Equals(value) != true)) {
                    this.IntIDField = value;
                    this.RaisePropertyChanged("IntID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExpire {
            get {
                return this.IsExpireField;
            }
            set {
                if ((this.IsExpireField.Equals(value) != true)) {
                    this.IsExpireField = value;
                    this.RaisePropertyChanged("IsExpire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EasyTreeData", Namespace="http://schemas.datacontract.org/2004/07/DbServer.Model")]
    [System.SerializableAttribute()]
    public partial class EasyTreeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> checkedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] childrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iconClsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> @checked {
            get {
                return this.checkedField;
            }
            set {
                if ((this.checkedField.Equals(value) != true)) {
                    this.checkedField = value;
                    this.RaisePropertyChanged("checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] children {
            get {
                return this.childrenField;
            }
            set {
                if ((object.ReferenceEquals(this.childrenField, value) != true)) {
                    this.childrenField = value;
                    this.RaisePropertyChanged("children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iconCls {
            get {
                return this.iconClsField;
            }
            set {
                if ((object.ReferenceEquals(this.iconClsField, value) != true)) {
                    this.iconClsField = value;
                    this.RaisePropertyChanged("iconCls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTOAuth")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcFuncIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcSeqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcSysTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcWebIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcWinformTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCreate {
            get {
                return this.DtCreateField;
            }
            set {
                if ((this.DtCreateField.Equals(value) != true)) {
                    this.DtCreateField = value;
                    this.RaisePropertyChanged("DtCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEdit {
            get {
                return this.DtEditField;
            }
            set {
                if ((this.DtEditField.Equals(value) != true)) {
                    this.DtEditField = value;
                    this.RaisePropertyChanged("DtEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntDeleted {
            get {
                return this.IntDeletedField;
            }
            set {
                if ((this.IntDeletedField.Equals(value) != true)) {
                    this.IntDeletedField = value;
                    this.RaisePropertyChanged("IntDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntVisible {
            get {
                return this.IntVisibleField;
            }
            set {
                if ((this.IntVisibleField.Equals(value) != true)) {
                    this.IntVisibleField = value;
                    this.RaisePropertyChanged("IntVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreator {
            get {
                return this.NvcCreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorField, value) != true)) {
                    this.NvcCreatorField = value;
                    this.RaisePropertyChanged("NvcCreator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreatorID {
            get {
                return this.NvcCreatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorIDField, value) != true)) {
                    this.NvcCreatorIDField = value;
                    this.RaisePropertyChanged("NvcCreatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditor {
            get {
                return this.NvcEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorField, value) != true)) {
                    this.NvcEditorField = value;
                    this.RaisePropertyChanged("NvcEditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditorID {
            get {
                return this.NvcEditorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorIDField, value) != true)) {
                    this.NvcEditorIDField = value;
                    this.RaisePropertyChanged("NvcEditorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcFuncId {
            get {
                return this.NvcFuncIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcFuncIdField, value) != true)) {
                    this.NvcFuncIdField = value;
                    this.RaisePropertyChanged("NvcFuncId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcID {
            get {
                return this.NvcIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcIDField, value) != true)) {
                    this.NvcIDField = value;
                    this.RaisePropertyChanged("NvcID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcIcon {
            get {
                return this.NvcIconField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcIconField, value) != true)) {
                    this.NvcIconField = value;
                    this.RaisePropertyChanged("NvcIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcPID {
            get {
                return this.NvcPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcPIDField, value) != true)) {
                    this.NvcPIDField = value;
                    this.RaisePropertyChanged("NvcPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcSeq {
            get {
                return this.NvcSeqField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcSeqField, value) != true)) {
                    this.NvcSeqField = value;
                    this.RaisePropertyChanged("NvcSeq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcSysTypeID {
            get {
                return this.NvcSysTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcSysTypeIDField, value) != true)) {
                    this.NvcSysTypeIDField = value;
                    this.RaisePropertyChanged("NvcSysTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcUrl {
            get {
                return this.NvcUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcUrlField, value) != true)) {
                    this.NvcUrlField = value;
                    this.RaisePropertyChanged("NvcUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcWebIcon {
            get {
                return this.NvcWebIconField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcWebIconField, value) != true)) {
                    this.NvcWebIconField = value;
                    this.RaisePropertyChanged("NvcWebIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcWinformType {
            get {
                return this.NvcWinformTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcWinformTypeField, value) != true)) {
                    this.NvcWinformTypeField = value;
                    this.RaisePropertyChanged("NvcWinformType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OU", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTOAuth")]
    [System.SerializableAttribute()]
    public partial class OU : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcComIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcComNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcHandNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcInnerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcOuterPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcSortCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCreate {
            get {
                return this.DtCreateField;
            }
            set {
                if ((this.DtCreateField.Equals(value) != true)) {
                    this.DtCreateField = value;
                    this.RaisePropertyChanged("DtCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEdit {
            get {
                return this.DtEditField;
            }
            set {
                if ((this.DtEditField.Equals(value) != true)) {
                    this.DtEditField = value;
                    this.RaisePropertyChanged("DtEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntDeleted {
            get {
                return this.IntDeletedField;
            }
            set {
                if ((this.IntDeletedField.Equals(value) != true)) {
                    this.IntDeletedField = value;
                    this.RaisePropertyChanged("IntDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntEnabled {
            get {
                return this.IntEnabledField;
            }
            set {
                if ((this.IntEnabledField.Equals(value) != true)) {
                    this.IntEnabledField = value;
                    this.RaisePropertyChanged("IntEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntID {
            get {
                return this.IntIDField;
            }
            set {
                if ((this.IntIDField.Equals(value) != true)) {
                    this.IntIDField = value;
                    this.RaisePropertyChanged("IntID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntPID {
            get {
                return this.IntPIDField;
            }
            set {
                if ((this.IntPIDField.Equals(value) != true)) {
                    this.IntPIDField = value;
                    this.RaisePropertyChanged("IntPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcAddress {
            get {
                return this.NvcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcAddressField, value) != true)) {
                    this.NvcAddressField = value;
                    this.RaisePropertyChanged("NvcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCategory {
            get {
                return this.NvcCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCategoryField, value) != true)) {
                    this.NvcCategoryField = value;
                    this.RaisePropertyChanged("NvcCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcComID {
            get {
                return this.NvcComIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcComIDField, value) != true)) {
                    this.NvcComIDField = value;
                    this.RaisePropertyChanged("NvcComID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcComName {
            get {
                return this.NvcComNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcComNameField, value) != true)) {
                    this.NvcComNameField = value;
                    this.RaisePropertyChanged("NvcComName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreator {
            get {
                return this.NvcCreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorField, value) != true)) {
                    this.NvcCreatorField = value;
                    this.RaisePropertyChanged("NvcCreator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreatorID {
            get {
                return this.NvcCreatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorIDField, value) != true)) {
                    this.NvcCreatorIDField = value;
                    this.RaisePropertyChanged("NvcCreatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditor {
            get {
                return this.NvcEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorField, value) != true)) {
                    this.NvcEditorField = value;
                    this.RaisePropertyChanged("NvcEditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditorID {
            get {
                return this.NvcEditorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorIDField, value) != true)) {
                    this.NvcEditorIDField = value;
                    this.RaisePropertyChanged("NvcEditorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcHandNo {
            get {
                return this.NvcHandNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcHandNoField, value) != true)) {
                    this.NvcHandNoField = value;
                    this.RaisePropertyChanged("NvcHandNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcInnerPhone {
            get {
                return this.NvcInnerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcInnerPhoneField, value) != true)) {
                    this.NvcInnerPhoneField = value;
                    this.RaisePropertyChanged("NvcInnerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcNote {
            get {
                return this.NvcNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNoteField, value) != true)) {
                    this.NvcNoteField = value;
                    this.RaisePropertyChanged("NvcNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcOuterPhone {
            get {
                return this.NvcOuterPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcOuterPhoneField, value) != true)) {
                    this.NvcOuterPhoneField = value;
                    this.RaisePropertyChanged("NvcOuterPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcSortCode {
            get {
                return this.NvcSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcSortCodeField, value) != true)) {
                    this.NvcSortCodeField = value;
                    this.RaisePropertyChanged("NvcSortCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResult", Namespace="http://schemas.datacontract.org/2004/07/DbServer.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.LogonUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.Menu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.OU))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WHC.WaterFeeWeb.ServiceReference1.EasyTreeData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    public partial class CommonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] LstObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrData2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrData3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable Tbl1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable Tbl2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] LstObj {
            get {
                return this.LstObjField;
            }
            set {
                if ((object.ReferenceEquals(this.LstObjField, value) != true)) {
                    this.LstObjField = value;
                    this.RaisePropertyChanged("LstObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrData1 {
            get {
                return this.StrData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrData1Field, value) != true)) {
                    this.StrData1Field = value;
                    this.RaisePropertyChanged("StrData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrData2 {
            get {
                return this.StrData2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrData2Field, value) != true)) {
                    this.StrData2Field = value;
                    this.RaisePropertyChanged("StrData2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrData3 {
            get {
                return this.StrData3Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrData3Field, value) != true)) {
                    this.StrData3Field = value;
                    this.RaisePropertyChanged("StrData3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable Tbl1 {
            get {
                return this.Tbl1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Tbl1Field, value) != true)) {
                    this.Tbl1Field = value;
                    this.RaisePropertyChanged("Tbl1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable Tbl2 {
            get {
                return this.Tbl2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Tbl2Field, value) != true)) {
                    this.Tbl2Field = value;
                    this.RaisePropertyChanged("Tbl2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTOAuth")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcComIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcComNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcHandNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcSortCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCreate {
            get {
                return this.DtCreateField;
            }
            set {
                if ((this.DtCreateField.Equals(value) != true)) {
                    this.DtCreateField = value;
                    this.RaisePropertyChanged("DtCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEdit {
            get {
                return this.DtEditField;
            }
            set {
                if ((this.DtEditField.Equals(value) != true)) {
                    this.DtEditField = value;
                    this.RaisePropertyChanged("DtEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntDeleted {
            get {
                return this.IntDeletedField;
            }
            set {
                if ((this.IntDeletedField.Equals(value) != true)) {
                    this.IntDeletedField = value;
                    this.RaisePropertyChanged("IntDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntEnabled {
            get {
                return this.IntEnabledField;
            }
            set {
                if ((this.IntEnabledField.Equals(value) != true)) {
                    this.IntEnabledField = value;
                    this.RaisePropertyChanged("IntEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntID {
            get {
                return this.IntIDField;
            }
            set {
                if ((this.IntIDField.Equals(value) != true)) {
                    this.IntIDField = value;
                    this.RaisePropertyChanged("IntID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntPID {
            get {
                return this.IntPIDField;
            }
            set {
                if ((this.IntPIDField.Equals(value) != true)) {
                    this.IntPIDField = value;
                    this.RaisePropertyChanged("IntPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCategory {
            get {
                return this.NvcCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCategoryField, value) != true)) {
                    this.NvcCategoryField = value;
                    this.RaisePropertyChanged("NvcCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcComID {
            get {
                return this.NvcComIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcComIDField, value) != true)) {
                    this.NvcComIDField = value;
                    this.RaisePropertyChanged("NvcComID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcComName {
            get {
                return this.NvcComNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcComNameField, value) != true)) {
                    this.NvcComNameField = value;
                    this.RaisePropertyChanged("NvcComName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreator {
            get {
                return this.NvcCreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorField, value) != true)) {
                    this.NvcCreatorField = value;
                    this.RaisePropertyChanged("NvcCreator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreatorID {
            get {
                return this.NvcCreatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorIDField, value) != true)) {
                    this.NvcCreatorIDField = value;
                    this.RaisePropertyChanged("NvcCreatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditor {
            get {
                return this.NvcEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorField, value) != true)) {
                    this.NvcEditorField = value;
                    this.RaisePropertyChanged("NvcEditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditorID {
            get {
                return this.NvcEditorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorIDField, value) != true)) {
                    this.NvcEditorIDField = value;
                    this.RaisePropertyChanged("NvcEditorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcHandNo {
            get {
                return this.NvcHandNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcHandNoField, value) != true)) {
                    this.NvcHandNoField = value;
                    this.RaisePropertyChanged("NvcHandNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcNote {
            get {
                return this.NvcNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNoteField, value) != true)) {
                    this.NvcNoteField = value;
                    this.RaisePropertyChanged("NvcNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcSortCode {
            get {
                return this.NvcSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcSortCodeField, value) != true)) {
                    this.NvcSortCodeField = value;
                    this.RaisePropertyChanged("NvcSortCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTOAuth")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtBirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIsExpireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcComIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCreatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcDeptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEditorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcHandNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcHomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcIDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcOfficePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcQQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcSortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcWorkAddrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtBirthday {
            get {
                return this.DtBirthdayField;
            }
            set {
                if ((this.DtBirthdayField.Equals(value) != true)) {
                    this.DtBirthdayField = value;
                    this.RaisePropertyChanged("DtBirthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCreate {
            get {
                return this.DtCreateField;
            }
            set {
                if ((this.DtCreateField.Equals(value) != true)) {
                    this.DtCreateField = value;
                    this.RaisePropertyChanged("DtCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEdit {
            get {
                return this.DtEditField;
            }
            set {
                if ((this.DtEditField.Equals(value) != true)) {
                    this.DtEditField = value;
                    this.RaisePropertyChanged("DtEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntDeleted {
            get {
                return this.IntDeletedField;
            }
            set {
                if ((this.IntDeletedField.Equals(value) != true)) {
                    this.IntDeletedField = value;
                    this.RaisePropertyChanged("IntDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntID {
            get {
                return this.IntIDField;
            }
            set {
                if ((this.IntIDField.Equals(value) != true)) {
                    this.IntIDField = value;
                    this.RaisePropertyChanged("IntID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntIsExpire {
            get {
                return this.IntIsExpireField;
            }
            set {
                if ((this.IntIsExpireField.Equals(value) != true)) {
                    this.IntIsExpireField = value;
                    this.RaisePropertyChanged("IntIsExpire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcAddress {
            get {
                return this.NvcAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcAddressField, value) != true)) {
                    this.NvcAddressField = value;
                    this.RaisePropertyChanged("NvcAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcComID {
            get {
                return this.NvcComIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcComIDField, value) != true)) {
                    this.NvcComIDField = value;
                    this.RaisePropertyChanged("NvcComID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreator {
            get {
                return this.NvcCreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorField, value) != true)) {
                    this.NvcCreatorField = value;
                    this.RaisePropertyChanged("NvcCreator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCreatorID {
            get {
                return this.NvcCreatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCreatorIDField, value) != true)) {
                    this.NvcCreatorIDField = value;
                    this.RaisePropertyChanged("NvcCreatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcDeptID {
            get {
                return this.NvcDeptIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcDeptIDField, value) != true)) {
                    this.NvcDeptIDField = value;
                    this.RaisePropertyChanged("NvcDeptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditor {
            get {
                return this.NvcEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorField, value) != true)) {
                    this.NvcEditorField = value;
                    this.RaisePropertyChanged("NvcEditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEditorID {
            get {
                return this.NvcEditorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEditorIDField, value) != true)) {
                    this.NvcEditorIDField = value;
                    this.RaisePropertyChanged("NvcEditorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcEmail {
            get {
                return this.NvcEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcEmailField, value) != true)) {
                    this.NvcEmailField = value;
                    this.RaisePropertyChanged("NvcEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcFullName {
            get {
                return this.NvcFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcFullNameField, value) != true)) {
                    this.NvcFullNameField = value;
                    this.RaisePropertyChanged("NvcFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcGender {
            get {
                return this.NvcGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcGenderField, value) != true)) {
                    this.NvcGenderField = value;
                    this.RaisePropertyChanged("NvcGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcHandNo {
            get {
                return this.NvcHandNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcHandNoField, value) != true)) {
                    this.NvcHandNoField = value;
                    this.RaisePropertyChanged("NvcHandNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcHomePhone {
            get {
                return this.NvcHomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcHomePhoneField, value) != true)) {
                    this.NvcHomePhoneField = value;
                    this.RaisePropertyChanged("NvcHomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcIDCard {
            get {
                return this.NvcIDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcIDCardField, value) != true)) {
                    this.NvcIDCardField = value;
                    this.RaisePropertyChanged("NvcIDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcMobile {
            get {
                return this.NvcMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcMobileField, value) != true)) {
                    this.NvcMobileField = value;
                    this.RaisePropertyChanged("NvcMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcNickname {
            get {
                return this.NvcNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNicknameField, value) != true)) {
                    this.NvcNicknameField = value;
                    this.RaisePropertyChanged("NvcNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcNote {
            get {
                return this.NvcNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNoteField, value) != true)) {
                    this.NvcNoteField = value;
                    this.RaisePropertyChanged("NvcNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcOfficePhone {
            get {
                return this.NvcOfficePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcOfficePhoneField, value) != true)) {
                    this.NvcOfficePhoneField = value;
                    this.RaisePropertyChanged("NvcOfficePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcPassword {
            get {
                return this.NvcPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcPasswordField, value) != true)) {
                    this.NvcPasswordField = value;
                    this.RaisePropertyChanged("NvcPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcQQ {
            get {
                return this.NvcQQField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcQQField, value) != true)) {
                    this.NvcQQField = value;
                    this.RaisePropertyChanged("NvcQQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcSortCode {
            get {
                return this.NvcSortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcSortCodeField, value) != true)) {
                    this.NvcSortCodeField = value;
                    this.RaisePropertyChanged("NvcSortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcTitle {
            get {
                return this.NvcTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcTitleField, value) != true)) {
                    this.NvcTitleField = value;
                    this.RaisePropertyChanged("NvcTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcWorkAddr {
            get {
                return this.NvcWorkAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcWorkAddrField, value) != true)) {
                    this.NvcWorkAddrField = value;
                    this.RaisePropertyChanged("NvcWorkAddr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuthority")]
    public interface IAuthority {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_CheckUser", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_CheckUserResponse")]
        WHC.WaterFeeWeb.ServiceReference1.LogonUser Sys_Login_CheckUser(string sUserID, string sPass, string sUserIP, string sUserMAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_CheckUser", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_CheckUserResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.LogonUser> Sys_Login_CheckUserAsync(string sUserID, string sPass, string sUserIP, string sUserMAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_GetMenuByUserID", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_GetMenuByUserIDResponse")]
        string Sys_Login_GetMenuByUserID(int iUserID, string sSysTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_GetMenuByUserID", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_GetMenuByUserIDResponse")]
        System.Threading.Tasks.Task<string> Sys_Login_GetMenuByUserIDAsync(int iUserID, string sSysTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_ChangePass", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_ChangePassResponse")]
        string Sys_Login_ChangePass(int iUserID, string sOldPass, string sNewPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Login_ChangePass", ReplyAction="http://tempuri.org/IAuthority/Sys_Login_ChangePassResponse")]
        System.Threading.Tasks.Task<string> Sys_Login_ChangePassAsync(int iUserID, string sOldPass, string sNewPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_GetTreeResponse")]
        WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_Menu_GetTree(int iDeleted, int iVisible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_GetTreeResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_Menu_GetTreeAsync(int iDeleted, int iVisible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_GetSon", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_GetSonResponse")]
        System.Data.DataTable Sys_Menu_GetSon(string sMenuID, int iDeleted, int iVisible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_GetSon", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_GetSonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Sys_Menu_GetSonAsync(string sMenuID, int iDeleted, int iVisible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_QryResponse")]
        System.Data.DataTable Sys_Menu_Qry(WHC.WaterFeeWeb.ServiceReference1.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_QryResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Sys_Menu_QryAsync(WHC.WaterFeeWeb.ServiceReference1.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_OprResponse")]
        string Sys_Menu_Opr(WHC.WaterFeeWeb.ServiceReference1.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_OprResponse")]
        System.Threading.Tasks.Task<string> Sys_Menu_OprAsync(WHC.WaterFeeWeb.ServiceReference1.Menu menu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_BatchDel", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_BatchDelResponse")]
        string Sys_Menu_BatchDel(string[] LstStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Menu_BatchDel", ReplyAction="http://tempuri.org/IAuthority/Sys_Menu_BatchDelResponse")]
        System.Threading.Tasks.Task<string> Sys_Menu_BatchDelAsync(string[] LstStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_GetTreeResponse")]
        WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_GetTree(int iUserID, int iDeleted, int iEnabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_GetTreeResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_GetTreeAsync(int iUserID, int iDeleted, int iEnabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_GetTree_Level", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_GetTree_LevelResponse")]
        WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_GetTree_Level(int iType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_GetTree_Level", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_GetTree_LevelResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_GetTree_LevelAsync(int iType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Ou_GetByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Ou_GetByIDResponse")]
        System.Data.DataTable Sys_Ou_GetByID(int iOuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Ou_GetByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Ou_GetByIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Sys_Ou_GetByIDAsync(int iOuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_OprResponse")]
        string Sys_OU_Opr(WHC.WaterFeeWeb.ServiceReference1.OU OrgInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_OprResponse")]
        System.Threading.Tasks.Task<string> Sys_OU_OprAsync(WHC.WaterFeeWeb.ServiceReference1.OU OrgInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Menu_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_Menu_QryResponse")]
        WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_Menu_Qry(int iOuID, int iMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Menu_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_Menu_QryResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_Menu_QryAsync(int iOuID, int iMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Menu_Save", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_Menu_SaveResponse")]
        string Sys_OU_Menu_Save(int iOuID, string[] LstStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_OU_Menu_Save", ReplyAction="http://tempuri.org/IAuthority/Sys_OU_Menu_SaveResponse")]
        System.Threading.Tasks.Task<string> Sys_OU_Menu_SaveAsync(int iOuID, string[] LstStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetTreeResponse")]
        WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_Role_GetTree(int iUserID, int iDeleted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetTree", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetTreeResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_Role_GetTreeAsync(int iUserID, int iDeleted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetRoleMenuUserByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetRoleMenuUserByIDResponse")]
        WHC.WaterFeeWeb.ServiceReference1.CommonResult Sys_Role_GetRoleMenuUserByID(int iRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetRoleMenuUserByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetRoleMenuUserByIDResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.CommonResult> Sys_Role_GetRoleMenuUserByIDAsync(int iRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_OprResponse")]
        string Sys_Role_Opr(WHC.WaterFeeWeb.ServiceReference1.Role RoleInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_OprResponse")]
        System.Threading.Tasks.Task<string> Sys_Role_OprAsync(WHC.WaterFeeWeb.ServiceReference1.Role RoleInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_UserSave", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_UserSaveResponse")]
        string Sys_Role_UserSave(int iRoleID, int[] LstUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_UserSave", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_UserSaveResponse")]
        System.Threading.Tasks.Task<string> Sys_Role_UserSaveAsync(int iRoleID, int[] LstUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_MenuSave", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_MenuSaveResponse")]
        string Sys_Role_MenuSave(int iRoleID, string[] LstMenuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_MenuSave", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_MenuSaveResponse")]
        System.Threading.Tasks.Task<string> Sys_Role_MenuSaveAsync(int iRoleID, string[] LstMenuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetUserByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetUserByIDResponse")]
        System.Data.DataTable Sys_Role_GetUserByID(int iRoleID, int iOuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_Role_GetUserByID", ReplyAction="http://tempuri.org/IAuthority/Sys_Role_GetUserByIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Sys_Role_GetUserByIDAsync(int iRoleID, int iOuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_User_QryResponse")]
        System.Data.DataTable Sys_User_Qry(int iCode, WHC.WaterFeeWeb.ServiceReference1.User Usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Qry", ReplyAction="http://tempuri.org/IAuthority/Sys_User_QryResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Sys_User_QryAsync(int iCode, WHC.WaterFeeWeb.ServiceReference1.User Usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_User_OprResponse")]
        string Sys_User_Opr(WHC.WaterFeeWeb.ServiceReference1.User Usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Opr", ReplyAction="http://tempuri.org/IAuthority/Sys_User_OprResponse")]
        System.Threading.Tasks.Task<string> Sys_User_OprAsync(WHC.WaterFeeWeb.ServiceReference1.User Usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Del", ReplyAction="http://tempuri.org/IAuthority/Sys_User_DelResponse")]
        string Sys_User_Del(int iMode, int[] LstID, string sUserID, string sUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthority/Sys_User_Del", ReplyAction="http://tempuri.org/IAuthority/Sys_User_DelResponse")]
        System.Threading.Tasks.Task<string> Sys_User_DelAsync(int iMode, int[] LstID, string sUserID, string sUserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorityChannel : WHC.WaterFeeWeb.ServiceReference1.IAuthority, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorityClient : System.ServiceModel.ClientBase<WHC.WaterFeeWeb.ServiceReference1.IAuthority>, WHC.WaterFeeWeb.ServiceReference1.IAuthority {
        
        public AuthorityClient() {
        }
        
        public AuthorityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.LogonUser Sys_Login_CheckUser(string sUserID, string sPass, string sUserIP, string sUserMAC) {
            return base.Channel.Sys_Login_CheckUser(sUserID, sPass, sUserIP, sUserMAC);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.LogonUser> Sys_Login_CheckUserAsync(string sUserID, string sPass, string sUserIP, string sUserMAC) {
            return base.Channel.Sys_Login_CheckUserAsync(sUserID, sPass, sUserIP, sUserMAC);
        }
        
        public string Sys_Login_GetMenuByUserID(int iUserID, string sSysTypeID) {
            return base.Channel.Sys_Login_GetMenuByUserID(iUserID, sSysTypeID);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Login_GetMenuByUserIDAsync(int iUserID, string sSysTypeID) {
            return base.Channel.Sys_Login_GetMenuByUserIDAsync(iUserID, sSysTypeID);
        }
        
        public string Sys_Login_ChangePass(int iUserID, string sOldPass, string sNewPass) {
            return base.Channel.Sys_Login_ChangePass(iUserID, sOldPass, sNewPass);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Login_ChangePassAsync(int iUserID, string sOldPass, string sNewPass) {
            return base.Channel.Sys_Login_ChangePassAsync(iUserID, sOldPass, sNewPass);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_Menu_GetTree(int iDeleted, int iVisible) {
            return base.Channel.Sys_Menu_GetTree(iDeleted, iVisible);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_Menu_GetTreeAsync(int iDeleted, int iVisible) {
            return base.Channel.Sys_Menu_GetTreeAsync(iDeleted, iVisible);
        }
        
        public System.Data.DataTable Sys_Menu_GetSon(string sMenuID, int iDeleted, int iVisible) {
            return base.Channel.Sys_Menu_GetSon(sMenuID, iDeleted, iVisible);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Sys_Menu_GetSonAsync(string sMenuID, int iDeleted, int iVisible) {
            return base.Channel.Sys_Menu_GetSonAsync(sMenuID, iDeleted, iVisible);
        }
        
        public System.Data.DataTable Sys_Menu_Qry(WHC.WaterFeeWeb.ServiceReference1.Menu menu) {
            return base.Channel.Sys_Menu_Qry(menu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Sys_Menu_QryAsync(WHC.WaterFeeWeb.ServiceReference1.Menu menu) {
            return base.Channel.Sys_Menu_QryAsync(menu);
        }
        
        public string Sys_Menu_Opr(WHC.WaterFeeWeb.ServiceReference1.Menu menu) {
            return base.Channel.Sys_Menu_Opr(menu);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Menu_OprAsync(WHC.WaterFeeWeb.ServiceReference1.Menu menu) {
            return base.Channel.Sys_Menu_OprAsync(menu);
        }
        
        public string Sys_Menu_BatchDel(string[] LstStr) {
            return base.Channel.Sys_Menu_BatchDel(LstStr);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Menu_BatchDelAsync(string[] LstStr) {
            return base.Channel.Sys_Menu_BatchDelAsync(LstStr);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_GetTree(int iUserID, int iDeleted, int iEnabled) {
            return base.Channel.Sys_OU_GetTree(iUserID, iDeleted, iEnabled);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_GetTreeAsync(int iUserID, int iDeleted, int iEnabled) {
            return base.Channel.Sys_OU_GetTreeAsync(iUserID, iDeleted, iEnabled);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_GetTree_Level(int iType) {
            return base.Channel.Sys_OU_GetTree_Level(iType);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_GetTree_LevelAsync(int iType) {
            return base.Channel.Sys_OU_GetTree_LevelAsync(iType);
        }
        
        public System.Data.DataTable Sys_Ou_GetByID(int iOuID) {
            return base.Channel.Sys_Ou_GetByID(iOuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Sys_Ou_GetByIDAsync(int iOuID) {
            return base.Channel.Sys_Ou_GetByIDAsync(iOuID);
        }
        
        public string Sys_OU_Opr(WHC.WaterFeeWeb.ServiceReference1.OU OrgInfo) {
            return base.Channel.Sys_OU_Opr(OrgInfo);
        }
        
        public System.Threading.Tasks.Task<string> Sys_OU_OprAsync(WHC.WaterFeeWeb.ServiceReference1.OU OrgInfo) {
            return base.Channel.Sys_OU_OprAsync(OrgInfo);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_OU_Menu_Qry(int iOuID, int iMode) {
            return base.Channel.Sys_OU_Menu_Qry(iOuID, iMode);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_OU_Menu_QryAsync(int iOuID, int iMode) {
            return base.Channel.Sys_OU_Menu_QryAsync(iOuID, iMode);
        }
        
        public string Sys_OU_Menu_Save(int iOuID, string[] LstStr) {
            return base.Channel.Sys_OU_Menu_Save(iOuID, LstStr);
        }
        
        public System.Threading.Tasks.Task<string> Sys_OU_Menu_SaveAsync(int iOuID, string[] LstStr) {
            return base.Channel.Sys_OU_Menu_SaveAsync(iOuID, LstStr);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[] Sys_Role_GetTree(int iUserID, int iDeleted) {
            return base.Channel.Sys_Role_GetTree(iUserID, iDeleted);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.EasyTreeData[]> Sys_Role_GetTreeAsync(int iUserID, int iDeleted) {
            return base.Channel.Sys_Role_GetTreeAsync(iUserID, iDeleted);
        }
        
        public WHC.WaterFeeWeb.ServiceReference1.CommonResult Sys_Role_GetRoleMenuUserByID(int iRoleID) {
            return base.Channel.Sys_Role_GetRoleMenuUserByID(iRoleID);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.ServiceReference1.CommonResult> Sys_Role_GetRoleMenuUserByIDAsync(int iRoleID) {
            return base.Channel.Sys_Role_GetRoleMenuUserByIDAsync(iRoleID);
        }
        
        public string Sys_Role_Opr(WHC.WaterFeeWeb.ServiceReference1.Role RoleInfo) {
            return base.Channel.Sys_Role_Opr(RoleInfo);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Role_OprAsync(WHC.WaterFeeWeb.ServiceReference1.Role RoleInfo) {
            return base.Channel.Sys_Role_OprAsync(RoleInfo);
        }
        
        public string Sys_Role_UserSave(int iRoleID, int[] LstUserID) {
            return base.Channel.Sys_Role_UserSave(iRoleID, LstUserID);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Role_UserSaveAsync(int iRoleID, int[] LstUserID) {
            return base.Channel.Sys_Role_UserSaveAsync(iRoleID, LstUserID);
        }
        
        public string Sys_Role_MenuSave(int iRoleID, string[] LstMenuID) {
            return base.Channel.Sys_Role_MenuSave(iRoleID, LstMenuID);
        }
        
        public System.Threading.Tasks.Task<string> Sys_Role_MenuSaveAsync(int iRoleID, string[] LstMenuID) {
            return base.Channel.Sys_Role_MenuSaveAsync(iRoleID, LstMenuID);
        }
        
        public System.Data.DataTable Sys_Role_GetUserByID(int iRoleID, int iOuID) {
            return base.Channel.Sys_Role_GetUserByID(iRoleID, iOuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Sys_Role_GetUserByIDAsync(int iRoleID, int iOuID) {
            return base.Channel.Sys_Role_GetUserByIDAsync(iRoleID, iOuID);
        }
        
        public System.Data.DataTable Sys_User_Qry(int iCode, WHC.WaterFeeWeb.ServiceReference1.User Usr) {
            return base.Channel.Sys_User_Qry(iCode, Usr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Sys_User_QryAsync(int iCode, WHC.WaterFeeWeb.ServiceReference1.User Usr) {
            return base.Channel.Sys_User_QryAsync(iCode, Usr);
        }
        
        public string Sys_User_Opr(WHC.WaterFeeWeb.ServiceReference1.User Usr) {
            return base.Channel.Sys_User_Opr(Usr);
        }
        
        public System.Threading.Tasks.Task<string> Sys_User_OprAsync(WHC.WaterFeeWeb.ServiceReference1.User Usr) {
            return base.Channel.Sys_User_OprAsync(Usr);
        }
        
        public string Sys_User_Del(int iMode, int[] LstID, string sUserID, string sUserName) {
            return base.Channel.Sys_User_Del(iMode, LstID, sUserID, sUserName);
        }
        
        public System.Threading.Tasks.Task<string> Sys_User_DelAsync(int iMode, int[] LstID, string sUserID, string sUserName) {
            return base.Channel.Sys_User_DelAsync(iMode, LstID, sUserID, sUserName);
        }
    }
}
