//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHC.WaterFeeWeb.DbServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Concentrator", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTO")]
    [System.SerializableAttribute()]
    public partial class Concentrator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtLastUpdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCmpCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCommModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntEndCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntFreqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntProtocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntUpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcParamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcSimNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtLastUpd {
            get {
                return this.DtLastUpdField;
            }
            set {
                if ((this.DtLastUpdField.Equals(value) != true)) {
                    this.DtLastUpdField = value;
                    this.RaisePropertyChanged("DtLastUpd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntAreaCode {
            get {
                return this.IntAreaCodeField;
            }
            set {
                if ((this.IntAreaCodeField.Equals(value) != true)) {
                    this.IntAreaCodeField = value;
                    this.RaisePropertyChanged("IntAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCOM {
            get {
                return this.IntCOMField;
            }
            set {
                if ((this.IntCOMField.Equals(value) != true)) {
                    this.IntCOMField = value;
                    this.RaisePropertyChanged("IntCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCmpCode {
            get {
                return this.IntCmpCodeField;
            }
            set {
                if ((this.IntCmpCodeField.Equals(value) != true)) {
                    this.IntCmpCodeField = value;
                    this.RaisePropertyChanged("IntCmpCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCommMode {
            get {
                return this.IntCommModeField;
            }
            set {
                if ((this.IntCommModeField.Equals(value) != true)) {
                    this.IntCommModeField = value;
                    this.RaisePropertyChanged("IntCommMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCount {
            get {
                return this.IntCountField;
            }
            set {
                if ((this.IntCountField.Equals(value) != true)) {
                    this.IntCountField = value;
                    this.RaisePropertyChanged("IntCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntEndCode {
            get {
                return this.IntEndCodeField;
            }
            set {
                if ((this.IntEndCodeField.Equals(value) != true)) {
                    this.IntEndCodeField = value;
                    this.RaisePropertyChanged("IntEndCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntFreq {
            get {
                return this.IntFreqField;
            }
            set {
                if ((this.IntFreqField.Equals(value) != true)) {
                    this.IntFreqField = value;
                    this.RaisePropertyChanged("IntFreq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntID {
            get {
                return this.IntIDField;
            }
            set {
                if ((this.IntIDField.Equals(value) != true)) {
                    this.IntIDField = value;
                    this.RaisePropertyChanged("IntID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntOnline {
            get {
                return this.IntOnlineField;
            }
            set {
                if ((this.IntOnlineField.Equals(value) != true)) {
                    this.IntOnlineField = value;
                    this.RaisePropertyChanged("IntOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntProtocol {
            get {
                return this.IntProtocolField;
            }
            set {
                if ((this.IntProtocolField.Equals(value) != true)) {
                    this.IntProtocolField = value;
                    this.RaisePropertyChanged("IntProtocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntStatus {
            get {
                return this.IntStatusField;
            }
            set {
                if ((this.IntStatusField.Equals(value) != true)) {
                    this.IntStatusField = value;
                    this.RaisePropertyChanged("IntStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntUpID {
            get {
                return this.IntUpIDField;
            }
            set {
                if ((this.IntUpIDField.Equals(value) != true)) {
                    this.IntUpIDField = value;
                    this.RaisePropertyChanged("IntUpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcAddr {
            get {
                return this.NvcAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcAddrField, value) != true)) {
                    this.NvcAddrField = value;
                    this.RaisePropertyChanged("NvcAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcAddr {
            get {
                return this.VcAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.VcAddrField, value) != true)) {
                    this.VcAddrField = value;
                    this.RaisePropertyChanged("VcAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcParam {
            get {
                return this.VcParamField;
            }
            set {
                if ((object.ReferenceEquals(this.VcParamField, value) != true)) {
                    this.VcParamField = value;
                    this.RaisePropertyChanged("VcParam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcSimNo {
            get {
                return this.VcSimNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcSimNoField, value) != true)) {
                    this.VcSimNoField = value;
                    this.RaisePropertyChanged("VcSimNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EasyTreeData", Namespace="http://schemas.datacontract.org/2004/07/DbServer.Model")]
    [System.SerializableAttribute()]
    public partial class EasyTreeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> checkedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[] childrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iconClsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> @checked {
            get {
                return this.checkedField;
            }
            set {
                if ((this.checkedField.Equals(value) != true)) {
                    this.checkedField = value;
                    this.RaisePropertyChanged("checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[] children {
            get {
                return this.childrenField;
            }
            set {
                if ((object.ReferenceEquals(this.childrenField, value) != true)) {
                    this.childrenField = value;
                    this.RaisePropertyChanged("children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iconCls {
            get {
                return this.iconClsField;
            }
            set {
                if ((object.ReferenceEquals(this.iconClsField, value) != true)) {
                    this.iconClsField = value;
                    this.RaisePropertyChanged("iconCls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTO")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DteCancelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DteOpenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntAccModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntAvgUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntEndCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntPriceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcCustTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcInvAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcInvNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcVillageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcAddrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcContractNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcIDNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcNameCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcRoomNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcTelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcUnitNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcWechatNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DteCancel {
            get {
                return this.DteCancelField;
            }
            set {
                if ((this.DteCancelField.Equals(value) != true)) {
                    this.DteCancelField = value;
                    this.RaisePropertyChanged("DteCancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DteOpen {
            get {
                return this.DteOpenField;
            }
            set {
                if ((this.DteOpenField.Equals(value) != true)) {
                    this.DteOpenField = value;
                    this.RaisePropertyChanged("DteOpen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntAccMode {
            get {
                return this.IntAccModeField;
            }
            set {
                if ((this.IntAccModeField.Equals(value) != true)) {
                    this.IntAccModeField = value;
                    this.RaisePropertyChanged("IntAccMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntAvgUsed {
            get {
                return this.IntAvgUsedField;
            }
            set {
                if ((this.IntAvgUsedField.Equals(value) != true)) {
                    this.IntAvgUsedField = value;
                    this.RaisePropertyChanged("IntAvgUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntEndCode {
            get {
                return this.IntEndCodeField;
            }
            set {
                if ((this.IntEndCodeField.Equals(value) != true)) {
                    this.IntEndCodeField = value;
                    this.RaisePropertyChanged("IntEndCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntNo {
            get {
                return this.IntNoField;
            }
            set {
                if ((this.IntNoField.Equals(value) != true)) {
                    this.IntNoField = value;
                    this.RaisePropertyChanged("IntNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntNumber {
            get {
                return this.IntNumberField;
            }
            set {
                if ((this.IntNumberField.Equals(value) != true)) {
                    this.IntNumberField = value;
                    this.RaisePropertyChanged("IntNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntPriceNo {
            get {
                return this.IntPriceNoField;
            }
            set {
                if ((this.IntPriceNoField.Equals(value) != true)) {
                    this.IntPriceNoField = value;
                    this.RaisePropertyChanged("IntPriceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntStatus {
            get {
                return this.IntStatusField;
            }
            set {
                if ((this.IntStatusField.Equals(value) != true)) {
                    this.IntStatusField = value;
                    this.RaisePropertyChanged("IntStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntUserID {
            get {
                return this.IntUserIDField;
            }
            set {
                if ((this.IntUserIDField.Equals(value) != true)) {
                    this.IntUserIDField = value;
                    this.RaisePropertyChanged("IntUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcAddr {
            get {
                return this.NvcAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcAddrField, value) != true)) {
                    this.NvcAddrField = value;
                    this.RaisePropertyChanged("NvcAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcCustType {
            get {
                return this.NvcCustTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcCustTypeField, value) != true)) {
                    this.NvcCustTypeField = value;
                    this.RaisePropertyChanged("NvcCustType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcInvAddr {
            get {
                return this.NvcInvAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcInvAddrField, value) != true)) {
                    this.NvcInvAddrField = value;
                    this.RaisePropertyChanged("NvcInvAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcInvName {
            get {
                return this.NvcInvNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcInvNameField, value) != true)) {
                    this.NvcInvNameField = value;
                    this.RaisePropertyChanged("NvcInvName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcVillage {
            get {
                return this.NvcVillageField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcVillageField, value) != true)) {
                    this.NvcVillageField = value;
                    this.RaisePropertyChanged("NvcVillage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcAddrCode {
            get {
                return this.VcAddrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VcAddrCodeField, value) != true)) {
                    this.VcAddrCodeField = value;
                    this.RaisePropertyChanged("VcAddrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcBuilding {
            get {
                return this.VcBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.VcBuildingField, value) != true)) {
                    this.VcBuildingField = value;
                    this.RaisePropertyChanged("VcBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcContractNo {
            get {
                return this.VcContractNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcContractNoField, value) != true)) {
                    this.VcContractNoField = value;
                    this.RaisePropertyChanged("VcContractNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcIDNo {
            get {
                return this.VcIDNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcIDNoField, value) != true)) {
                    this.VcIDNoField = value;
                    this.RaisePropertyChanged("VcIDNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcMobile {
            get {
                return this.VcMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.VcMobileField, value) != true)) {
                    this.VcMobileField = value;
                    this.RaisePropertyChanged("VcMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcNameCode {
            get {
                return this.VcNameCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VcNameCodeField, value) != true)) {
                    this.VcNameCodeField = value;
                    this.RaisePropertyChanged("VcNameCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcRoomNum {
            get {
                return this.VcRoomNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VcRoomNumField, value) != true)) {
                    this.VcRoomNumField = value;
                    this.RaisePropertyChanged("VcRoomNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcTelNo {
            get {
                return this.VcTelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcTelNoField, value) != true)) {
                    this.VcTelNoField = value;
                    this.RaisePropertyChanged("VcTelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcUnitNum {
            get {
                return this.VcUnitNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VcUnitNumField, value) != true)) {
                    this.VcUnitNumField = value;
                    this.RaisePropertyChanged("VcUnitNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcWechatNo {
            get {
                return this.VcWechatNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcWechatNoField, value) != true)) {
                    this.VcWechatNoField = value;
                    this.RaisePropertyChanged("VcWechatNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meter", Namespace="http://schemas.datacontract.org/2004/07/DbServer.DTO")]
    [System.SerializableAttribute()]
    public partial class Meter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtLastUpdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntAccountWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntAutoSwitchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntConIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IntCustCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCustNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCycleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntEndCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntOrigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntPriceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntPriceNo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntProtocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntReadFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntTopConIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntValveStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NvcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcAssetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VcBarCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtLastUpd {
            get {
                return this.DtLastUpdField;
            }
            set {
                if ((this.DtLastUpdField.Equals(value) != true)) {
                    this.DtLastUpdField = value;
                    this.RaisePropertyChanged("DtLastUpd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtOnline {
            get {
                return this.DtOnlineField;
            }
            set {
                if ((this.DtOnlineField.Equals(value) != true)) {
                    this.DtOnlineField = value;
                    this.RaisePropertyChanged("DtOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntAccountWay {
            get {
                return this.IntAccountWayField;
            }
            set {
                if ((this.IntAccountWayField.Equals(value) != true)) {
                    this.IntAccountWayField = value;
                    this.RaisePropertyChanged("IntAccountWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntAutoSwitch {
            get {
                return this.IntAutoSwitchField;
            }
            set {
                if ((this.IntAutoSwitchField.Equals(value) != true)) {
                    this.IntAutoSwitchField = value;
                    this.RaisePropertyChanged("IntAutoSwitch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntConID {
            get {
                return this.IntConIDField;
            }
            set {
                if ((this.IntConIDField.Equals(value) != true)) {
                    this.IntConIDField = value;
                    this.RaisePropertyChanged("IntConID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntCustCode {
            get {
                return this.IntCustCodeField;
            }
            set {
                if ((this.IntCustCodeField.Equals(value) != true)) {
                    this.IntCustCodeField = value;
                    this.RaisePropertyChanged("IntCustCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCustNO {
            get {
                return this.IntCustNOField;
            }
            set {
                if ((this.IntCustNOField.Equals(value) != true)) {
                    this.IntCustNOField = value;
                    this.RaisePropertyChanged("IntCustNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCycle {
            get {
                return this.IntCycleField;
            }
            set {
                if ((this.IntCycleField.Equals(value) != true)) {
                    this.IntCycleField = value;
                    this.RaisePropertyChanged("IntCycle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntEndCode {
            get {
                return this.IntEndCodeField;
            }
            set {
                if ((this.IntEndCodeField.Equals(value) != true)) {
                    this.IntEndCodeField = value;
                    this.RaisePropertyChanged("IntEndCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntMP {
            get {
                return this.IntMPField;
            }
            set {
                if ((this.IntMPField.Equals(value) != true)) {
                    this.IntMPField = value;
                    this.RaisePropertyChanged("IntMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntOnline {
            get {
                return this.IntOnlineField;
            }
            set {
                if ((this.IntOnlineField.Equals(value) != true)) {
                    this.IntOnlineField = value;
                    this.RaisePropertyChanged("IntOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntOrig {
            get {
                return this.IntOrigField;
            }
            set {
                if ((this.IntOrigField.Equals(value) != true)) {
                    this.IntOrigField = value;
                    this.RaisePropertyChanged("IntOrig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntPriceNo {
            get {
                return this.IntPriceNoField;
            }
            set {
                if ((this.IntPriceNoField.Equals(value) != true)) {
                    this.IntPriceNoField = value;
                    this.RaisePropertyChanged("IntPriceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntPriceNo2 {
            get {
                return this.IntPriceNo2Field;
            }
            set {
                if ((this.IntPriceNo2Field.Equals(value) != true)) {
                    this.IntPriceNo2Field = value;
                    this.RaisePropertyChanged("IntPriceNo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntProtocol {
            get {
                return this.IntProtocolField;
            }
            set {
                if ((this.IntProtocolField.Equals(value) != true)) {
                    this.IntProtocolField = value;
                    this.RaisePropertyChanged("IntProtocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntReadFlag {
            get {
                return this.IntReadFlagField;
            }
            set {
                if ((this.IntReadFlagField.Equals(value) != true)) {
                    this.IntReadFlagField = value;
                    this.RaisePropertyChanged("IntReadFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntStatus {
            get {
                return this.IntStatusField;
            }
            set {
                if ((this.IntStatusField.Equals(value) != true)) {
                    this.IntStatusField = value;
                    this.RaisePropertyChanged("IntStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntTopConID {
            get {
                return this.IntTopConIDField;
            }
            set {
                if ((this.IntTopConIDField.Equals(value) != true)) {
                    this.IntTopConIDField = value;
                    this.RaisePropertyChanged("IntTopConID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntValveState {
            get {
                return this.IntValveStateField;
            }
            set {
                if ((this.IntValveStateField.Equals(value) != true)) {
                    this.IntValveStateField = value;
                    this.RaisePropertyChanged("IntValveState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumRatio {
            get {
                return this.NumRatioField;
            }
            set {
                if ((this.NumRatioField.Equals(value) != true)) {
                    this.NumRatioField = value;
                    this.RaisePropertyChanged("NumRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcAddr {
            get {
                return this.NvcAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcAddrField, value) != true)) {
                    this.NvcAddrField = value;
                    this.RaisePropertyChanged("NvcAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NvcName {
            get {
                return this.NvcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NvcNameField, value) != true)) {
                    this.NvcNameField = value;
                    this.RaisePropertyChanged("NvcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcAddr {
            get {
                return this.VcAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.VcAddrField, value) != true)) {
                    this.VcAddrField = value;
                    this.RaisePropertyChanged("VcAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcAssetNo {
            get {
                return this.VcAssetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VcAssetNoField, value) != true)) {
                    this.VcAssetNoField = value;
                    this.RaisePropertyChanged("VcAssetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VcBarCode {
            get {
                return this.VcBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VcBarCodeField, value) != true)) {
                    this.VcBarCodeField = value;
                    this.RaisePropertyChanged("VcBarCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbServiceReference.IServiceDb")]
    public interface IServiceDb {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Qry", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_QryResponse")]
        System.Data.DataTable ArcConcentrator_Qry(int iCode, WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Qry", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_QryResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ArcConcentrator_QryAsync(int iCode, WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Ins", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_InsResponse")]
        string ArcConcentrator_Ins(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Ins", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_InsResponse")]
        System.Threading.Tasks.Task<string> ArcConcentrator_InsAsync(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Upd", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_UpdResponse")]
        string ArcConcentrator_Upd(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_Upd", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_UpdResponse")]
        System.Threading.Tasks.Task<string> ArcConcentrator_UpdAsync(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_GetDict_Status", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_GetDict_StatusResponse")]
        string ArcConcentrator_GetDict_Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_GetDict_Status", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_GetDict_StatusResponse")]
        System.Threading.Tasks.Task<string> ArcConcentrator_GetDict_StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_GetTree_Level", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_GetTree_LevelResponse")]
        WHC.WaterFeeWeb.DbServiceReference.Concentrator[] ArcConcentrator_GetTree_Level(int iCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcConcentrator_GetTree_Level", ReplyAction="http://tempuri.org/IServiceDb/ArcConcentrator_GetTree_LevelResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.DbServiceReference.Concentrator[]> ArcConcentrator_GetTree_LevelAsync(int iCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustomer_TreeCommunity", ReplyAction="http://tempuri.org/IServiceDb/ArcCustomer_TreeCommunityResponse")]
        WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[] ArcCustomer_TreeCommunity(int iCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustomer_TreeCommunity", ReplyAction="http://tempuri.org/IServiceDb/ArcCustomer_TreeCommunityResponse")]
        System.Threading.Tasks.Task<WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[]> ArcCustomer_TreeCommunityAsync(int iCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustomer_Qry", ReplyAction="http://tempuri.org/IServiceDb/ArcCustomer_QryResponse")]
        System.Data.DataTable ArcCustomer_Qry(int iCode, WHC.WaterFeeWeb.DbServiceReference.Customer Cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustomer_Qry", ReplyAction="http://tempuri.org/IServiceDb/ArcCustomer_QryResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ArcCustomer_QryAsync(int iCode, WHC.WaterFeeWeb.DbServiceReference.Customer Cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustMeter_Ins", ReplyAction="http://tempuri.org/IServiceDb/ArcCustMeter_InsResponse")]
        string ArcCustMeter_Ins(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustMeter_Ins", ReplyAction="http://tempuri.org/IServiceDb/ArcCustMeter_InsResponse")]
        System.Threading.Tasks.Task<string> ArcCustMeter_InsAsync(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustMeter_Upd", ReplyAction="http://tempuri.org/IServiceDb/ArcCustMeter_UpdResponse")]
        string ArcCustMeter_Upd(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDb/ArcCustMeter_Upd", ReplyAction="http://tempuri.org/IServiceDb/ArcCustMeter_UpdResponse")]
        System.Threading.Tasks.Task<string> ArcCustMeter_UpdAsync(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDbChannel : WHC.WaterFeeWeb.DbServiceReference.IServiceDb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDbClient : System.ServiceModel.ClientBase<WHC.WaterFeeWeb.DbServiceReference.IServiceDb>, WHC.WaterFeeWeb.DbServiceReference.IServiceDb {
        
        public ServiceDbClient() {
        }
        
        public ServiceDbClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDbClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDbClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDbClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ArcConcentrator_Qry(int iCode, WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_Qry(iCode, Concent);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ArcConcentrator_QryAsync(int iCode, WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_QryAsync(iCode, Concent);
        }
        
        public string ArcConcentrator_Ins(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_Ins(Concent);
        }
        
        public System.Threading.Tasks.Task<string> ArcConcentrator_InsAsync(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_InsAsync(Concent);
        }
        
        public string ArcConcentrator_Upd(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_Upd(Concent);
        }
        
        public System.Threading.Tasks.Task<string> ArcConcentrator_UpdAsync(WHC.WaterFeeWeb.DbServiceReference.Concentrator Concent) {
            return base.Channel.ArcConcentrator_UpdAsync(Concent);
        }
        
        public string ArcConcentrator_GetDict_Status() {
            return base.Channel.ArcConcentrator_GetDict_Status();
        }
        
        public System.Threading.Tasks.Task<string> ArcConcentrator_GetDict_StatusAsync() {
            return base.Channel.ArcConcentrator_GetDict_StatusAsync();
        }
        
        public WHC.WaterFeeWeb.DbServiceReference.Concentrator[] ArcConcentrator_GetTree_Level(int iCode) {
            return base.Channel.ArcConcentrator_GetTree_Level(iCode);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.DbServiceReference.Concentrator[]> ArcConcentrator_GetTree_LevelAsync(int iCode) {
            return base.Channel.ArcConcentrator_GetTree_LevelAsync(iCode);
        }
        
        public WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[] ArcCustomer_TreeCommunity(int iCode) {
            return base.Channel.ArcCustomer_TreeCommunity(iCode);
        }
        
        public System.Threading.Tasks.Task<WHC.WaterFeeWeb.DbServiceReference.EasyTreeData[]> ArcCustomer_TreeCommunityAsync(int iCode) {
            return base.Channel.ArcCustomer_TreeCommunityAsync(iCode);
        }
        
        public System.Data.DataTable ArcCustomer_Qry(int iCode, WHC.WaterFeeWeb.DbServiceReference.Customer Cust) {
            return base.Channel.ArcCustomer_Qry(iCode, Cust);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ArcCustomer_QryAsync(int iCode, WHC.WaterFeeWeb.DbServiceReference.Customer Cust) {
            return base.Channel.ArcCustomer_QryAsync(iCode, Cust);
        }
        
        public string ArcCustMeter_Ins(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter) {
            return base.Channel.ArcCustMeter_Ins(Cust, meter);
        }
        
        public System.Threading.Tasks.Task<string> ArcCustMeter_InsAsync(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter) {
            return base.Channel.ArcCustMeter_InsAsync(Cust, meter);
        }
        
        public string ArcCustMeter_Upd(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter) {
            return base.Channel.ArcCustMeter_Upd(Cust, meter);
        }
        
        public System.Threading.Tasks.Task<string> ArcCustMeter_UpdAsync(WHC.WaterFeeWeb.DbServiceReference.Customer Cust, WHC.WaterFeeWeb.DbServiceReference.Meter meter) {
            return base.Channel.ArcCustMeter_UpdAsync(Cust, meter);
        }
    }
}
